/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/digest/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Digest */
        get: operations["latest_digest_digest_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brief/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Brief State
         * @description Live quotes for the brief set (fixed core + user mega-caps).
         */
        get: operations["brief_state_brief_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brief/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Brief Latest
         * @description The most recently delivered brief snapshot (from the in-app ledger mirror).
         *
         *     "Nothing delivered yet" is an expected state, not an error — 200/null, like the digest.
         */
        get: operations["brief_latest_brief_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brief/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Brief
         * @description On-demand market brief: generate the snapshot and deliver it now (per brief channels).
         */
        post: operations["run_brief_brief_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Companies
         * @description Companies, optionally filtered by coverage tier (e.g. the watchlist).
         */
        get: operations["list_companies_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Detail */
        get: operations["company_detail_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Watchlist
         * @description Promote a company to the watchlist (deep coverage) or demote it back to discovered.
         *
         *     Watchlist membership is the ``coverage_tier`` column on ``companies`` — promotion/demotion is
         *     a single tier flip. Per-company alert thresholds live on ``user_preferences``.
         */
        post: operations["update_watchlist_companies__company_id__watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/industries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Industries
         * @description All industries in the controlled vocabulary, with the user's critical flags.
         */
        get: operations["list_industries_industries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/industries/{industry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Industry View */
        get: operations["industry_view_industries__industry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/industries/{industry_id}/flag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flag Industry
         * @description Add/remove an industry from the user's critical-industries list.
         */
        post: operations["flag_industry_industries__industry_id__flag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inbox */
        get: operations["inbox_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_inbox__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox/{notification_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss */
        post: operations["dismiss_inbox__notification_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences/brief-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Brief User
         * @description Replace the user-chosen brief mega-caps (the fixed core lives in config, untouched).
         */
        put: operations["update_brief_user_preferences_brief_user_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Budget
         * @description Set (or clear) the weekly token budget the agent self-paces against.
         */
        put: operations["update_budget_preferences_budget_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Channels
         * @description Replace notification routing: addresses + which channels the digest and brief use.
         */
        put: operations["update_channels_preferences_channels_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Research sessions, most recently active first.
         */
        get: operations["list_sessions_research_get"];
        put?: never;
        /**
         * Open Session
         * @description Open a research session and run it in the background (202 + state_id to poll).
         *
         *     Gates are checked synchronously so a blocked request fails loudly here instead of silently
         *     in the background: 409 when the weekly budget is exhausted or the active-session cap is hit.
         *     Re-posting the topic of an already-open session is idempotent — the existing ``state_id``
         *     comes back instead of a duplicate session (absorbs double-submits).
         */
        post: operations["open_session_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{state_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Detail
         * @description One session with its task trail and the source articles it has consulted.
         */
        get: operations["session_detail_research__state_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{state_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Session
         * @description Close a session, optionally promoting its findings to the durable analysis record.
         *
         *     Also answers the promotion question for an already-closed session (promote-only).
         */
        post: operations["close_session_research__state_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{state_id}/redirect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redirect Session
         * @description Steer an open session: update its topic and/or current task.
         *
         *     The next resume reconstructs context from the state row, so the redirect takes effect at the
         *     next wakeup. Direct ORM update — the tools-only rule constrains the AI, not the API.
         */
        post: operations["redirect_session_research__state_id__redirect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/followup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Followup
         * @description Transient scoped Q&A — the lightweight followup task; no session, nothing persisted.
         */
        post: operations["followup_research_followup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description The thread, oldest-first. Keyset pagination: pass ``before_id`` to page back.
         */
        get: operations["list_messages_chat_messages_get"];
        put?: never;
        /**
         * Post Message
         * @description Ask the agent. Returns the persisted [user, assistant] pair for the client to append.
         */
        post: operations["post_message_chat_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity
         * @description Running tasks (all of them) + the most recent terminal ones.
         */
        get: operations["activity_agent_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Budget
         * @description Weekly cap, spend over the trailing 7 days, and what remains (null = uncapped).
         */
        get: operations["budget_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityOut */
        ActivityOut: {
            /** Running */
            running: components["schemas"]["TaskOut"][];
            /** Recent */
            recent: components["schemas"]["TaskOut"][];
        };
        /** ArticleOut */
        ArticleOut: {
            /** News Event Id */
            news_event_id: number;
            /** Url */
            url: string;
            /** Source */
            source: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Headline */
            headline: string;
            /** Summary */
            summary: string;
            /** Significance */
            significance: number;
            /** Tickers */
            tickers: string[];
        };
        /** BriefInstrumentOut */
        BriefInstrumentOut: {
            /** Symbol */
            symbol: string;
            /** Label */
            label: string | null;
            /** Price */
            price: number | null;
            /** Change */
            change: number | null;
            /** Change Pct */
            change_pct: number | null;
        };
        /** BriefLatestOut */
        BriefLatestOut: {
            /** Title */
            title: string | null;
            /** Body */
            body: string | null;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
        };
        /** BriefStateOut */
        BriefStateOut: {
            /** Instruments */
            instruments: components["schemas"]["BriefInstrumentOut"][];
        };
        /** BriefUserUpdate */
        BriefUserUpdate: {
            /** Symbols */
            symbols: string[];
        };
        /** BudgetOut */
        BudgetOut: {
            /** Weekly Token Budget */
            weekly_token_budget: number | null;
            /** Spent 7D */
            spent_7d: number;
            /** Remaining */
            remaining: number | null;
        };
        /** BudgetUpdate */
        BudgetUpdate: {
            /** Weekly Token Budget */
            weekly_token_budget?: number | null;
        };
        /**
         * Channel
         * @enum {string}
         */
        Channel: "email" | "imessage" | "whatsapp" | "in_app";
        /**
         * ChannelsOut
         * @description Wire mirror of the ``UserChannels`` JSONB payload (kept separate per the four-model rule).
         */
        ChannelsOut: {
            /** Email */
            email?: string | null;
            /** Imessage */
            imessage?: string | null;
            /** Whatsapp */
            whatsapp?: string | null;
            /** Digest Channels */
            digest_channels?: string[];
            /** Brief Channels */
            brief_channels?: string[];
        };
        /** ChannelsUpdate */
        ChannelsUpdate: {
            /** Email */
            email?: string | null;
            /** Imessage */
            imessage?: string | null;
            /** Whatsapp */
            whatsapp?: string | null;
            /** Digest Channels */
            digest_channels?: string[];
            /** Brief Channels */
            brief_channels?: string[];
        };
        /** ChatMessageCreate */
        ChatMessageCreate: {
            /** Content */
            content: string;
            /** Company Id */
            company_id?: number | null;
            /** Industry Id */
            industry_id?: number | null;
        };
        /** ChatMessageOut */
        ChatMessageOut: {
            /** Id */
            id: number;
            role: components["schemas"]["ChatRole"];
            /** Content */
            content: string;
            /** News Event Ids */
            news_event_ids?: number[];
            /** Source Urls */
            source_urls?: string[];
            /** State Id */
            state_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ChatRole
         * @enum {string}
         */
        ChatRole: "user" | "assistant";
        /** CompanyDetail */
        CompanyDetail: {
            /** Company Id */
            company_id: number;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            coverage_tier: components["schemas"]["CoverageTier"];
            /** Sector */
            sector: string | null;
            /** Industry Id */
            industry_id: number | null;
            /** Exchange */
            exchange: string | null;
            /** Articles */
            articles: components["schemas"]["ArticleOut"][];
            /** Scores */
            scores: components["schemas"]["ScoreOut"][];
            /** Prose */
            prose: components["schemas"]["ProseOut"][];
        };
        /** CompanyListItem */
        CompanyListItem: {
            /** Company Id */
            company_id: number;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Industry Id */
            industry_id: number | null;
            coverage_tier: components["schemas"]["CoverageTier"];
        };
        /**
         * CoverageTier
         * @enum {string}
         */
        CoverageTier: "watchlist" | "industry_critical" | "discovered" | "archived";
        /** DigestSectionOut */
        DigestSectionOut: {
            /** Section Title */
            section_title: string;
            /** Snapshot */
            snapshot: string;
            /** Article Refs */
            article_refs: number[];
            /** Key Tickers */
            key_tickers: string[];
        };
        /** DigestView */
        DigestView: {
            /** Id */
            id: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Top Snapshot */
            top_snapshot: string | null;
            /** Sections */
            sections: components["schemas"]["DigestSectionOut"][];
            /** Source Event Ids */
            source_event_ids: number[];
        };
        /** FollowupRequest */
        FollowupRequest: {
            /** Query */
            query: string;
            /** Company Id */
            company_id?: number | null;
            /** Industry Id */
            industry_id?: number | null;
        };
        /** FollowupResponse */
        FollowupResponse: {
            /** Answer */
            answer: string;
            /**
             * Sources
             * @default []
             */
            sources: number[];
            /**
             * Source Urls
             * @default []
             */
            source_urls: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InboxItem */
        InboxItem: {
            /** Id */
            id: number;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            channel: components["schemas"]["Channel"];
            /** Template */
            template: string | null;
            /** Ref Type */
            ref_type: string | null;
            /** Ref Id */
            ref_id: number | null;
            /** Title */
            title?: string | null;
            /** Body */
            body?: string | null;
            /** Read At */
            read_at?: string | null;
            /** Dismissed At */
            dismissed_at?: string | null;
        };
        /** IndustryFlagUpdate */
        IndustryFlagUpdate: {
            /** Flagged */
            flagged: boolean;
        };
        /** IndustryListItem */
        IndustryListItem: {
            /** Industry Id */
            industry_id: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Flagged */
            flagged: boolean;
        };
        /** IndustryView */
        IndustryView: {
            /** Industry Id */
            industry_id: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Articles */
            articles: components["schemas"]["ArticleOut"][];
        };
        /** PreferencesOut */
        PreferencesOut: {
            /** Interested Sectors */
            interested_sectors: string[];
            /** Brief User */
            brief_user: string[];
            /** Critical Industries */
            critical_industries: number[];
            /** Weekly Token Budget */
            weekly_token_budget?: number | null;
            channels?: components["schemas"]["ChannelsOut"] | null;
        };
        /** ProseOut */
        ProseOut: {
            /** Kind */
            kind: string;
            /** Body */
            body: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Source Event Ids */
            source_event_ids: number[];
        };
        /** ResearchCloseRequest */
        ResearchCloseRequest: {
            /**
             * Promote
             * @default false
             */
            promote: boolean;
        };
        /** ResearchCloseResponse */
        ResearchCloseResponse: {
            /** State Id */
            state_id: number;
            /** Promoted */
            promoted: boolean;
            /** Closed */
            closed: boolean;
        };
        /** ResearchOpenRequest */
        ResearchOpenRequest: {
            /** Topic */
            topic: string;
            /** Company Id */
            company_id?: number | null;
            /** Industry Id */
            industry_id?: number | null;
        };
        /** ResearchOpenResponse */
        ResearchOpenResponse: {
            /** State Id */
            state_id: number;
            /**
             * Status
             * @default started
             * @constant
             */
            status: "started";
        };
        /** ResearchRedirectRequest */
        ResearchRedirectRequest: {
            /** Topic */
            topic?: string | null;
            /** Current Task */
            current_task?: string | null;
        };
        /** ResearchSessionDetail */
        ResearchSessionDetail: {
            /** State Id */
            state_id: number;
            /** Topic */
            topic: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "closed";
            /** Current Task */
            current_task: string | null;
            /** Findings */
            findings: string | null;
            /** Open Questions */
            open_questions: string | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Last Active At
             * Format: date-time
             */
            last_active_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Parent State Id */
            parent_state_id: number | null;
            /** Source Articles */
            source_articles?: components["schemas"]["ArticleOut"][];
            /** Source Urls */
            source_urls?: string[];
            /** Tasks */
            tasks?: components["schemas"]["TaskOut"][];
        };
        /** ResearchSessionOut */
        ResearchSessionOut: {
            /** State Id */
            state_id: number;
            /** Topic */
            topic: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "closed";
            /** Current Task */
            current_task: string | null;
            /** Findings */
            findings: string | null;
            /** Open Questions */
            open_questions: string | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Last Active At
             * Format: date-time
             */
            last_active_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Parent State Id */
            parent_state_id: number | null;
        };
        /** ScoreOut */
        ScoreOut: {
            /** Kind */
            kind: string;
            /** Score */
            score: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Data Through */
            data_through: string | null;
        };
        /**
         * StateStatus
         * @enum {string}
         */
        StateStatus: "open" | "closed";
        /** TaskOut */
        TaskOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Error Message */
            error_message: string | null;
            /** Tokens Used */
            tokens_used: number | null;
            /** State Id */
            state_id: number | null;
            /** Message */
            message?: string | null;
            /** Counts */
            counts?: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistUpdate */
        WatchlistUpdate: {
            /**
             * Action
             * @enum {string}
             */
            action: "promote" | "demote";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    latest_digest_digest_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestView"] | null;
                };
            };
        };
    };
    brief_state_brief_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefStateOut"];
                };
            };
        };
    };
    brief_latest_brief_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefLatestOut"] | null;
                };
            };
        };
    };
    run_brief_brief_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_companies_companies_get: {
        parameters: {
            query?: {
                tier?: components["schemas"]["CoverageTier"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_detail_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watchlist_companies__company_id__watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_industries_industries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustryListItem"][];
                };
            };
        };
    };
    industry_view_industries__industry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                industry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flag_industry_industries__industry_id__flag_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                industry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndustryFlagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inbox_inbox_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_inbox__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_inbox__notification_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
        };
    };
    update_brief_user_preferences_brief_user_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefUserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_budget_preferences_budget_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_channels_preferences_channels_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_research_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["StateStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_session_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchOpenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchOpenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_detail_research__state_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_session_research__state_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchCloseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchCloseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redirect_session_research__state_id__redirect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRedirectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    followup_research_followup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_chat_messages_get: {
        parameters: {
            query?: {
                limit?: number;
                before_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_chat_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_agent_activity_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    budget_budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
