"""initial schema

Revision ID: 2ee3043ce86a
Revises: 
Create Date: 2026-06-07 19:17:48.519341
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '2ee3043ce86a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector must exist before any VECTOR column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('analysis',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('fundamental', 'sentimental', 'event_driven', 'summary', name='analysis_type'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supporting_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis'))
    )
    op.create_index('ix_analysis_embedding_hnsw', 'analysis', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_analysis_type'), 'analysis', ['type'], unique=False)
    op.create_index('ix_analysis_type_generated', 'analysis', ['type', 'generated_at'], unique=False)
    op.create_table('cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cache'))
    )
    op.create_index('ix_cache_fetched_at', 'cache', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_cache_url'), 'cache', ['url'], unique=True)
    op.create_table('industries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industries'))
    )
    op.create_index(op.f('ix_industries_key'), 'industries', ['key'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel', sa.Enum('email', 'imessage', 'whatsapp', 'in_app', name='channel'), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('channel', 'content_hash', name=op.f('uq_notifications_channel'))
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_sent_at'), 'notifications', ['sent_at'], unique=False)
    op.create_table('research_state',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='state_status'), server_default='open', nullable=False),
    sa.Column('current_task', sa.Text(), nullable=True),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('open_questions', sa.Text(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_state_id', sa.BigInteger(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_state_id'], ['research_state.id'], name=op.f('fk_research_state_parent_state_id_research_state'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_state'))
    )
    op.create_index('ix_research_state_embedding_hnsw', 'research_state', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_research_state_parent_state_id'), 'research_state', ['parent_state_id'], unique=False)
    op.create_index(op.f('ix_research_state_status'), 'research_state', ['status'], unique=False)
    op.create_index('ix_research_state_status_active', 'research_state', ['status', 'last_active_at'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('interested_sectors', postgresql.ARRAY(sa.String(length=64)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('critical_industries', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=False),
    sa.Column('brief_user', postgresql.ARRAY(sa.String(length=20)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('default_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weekly_token_budget', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('sub_industry', sa.String(length=128), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('industry_id', sa.BigInteger(), nullable=True),
    sa.Column('coverage_tier', sa.Enum('watchlist', 'industry_critical', 'discovered', 'archived', name='coverage_tier'), server_default='discovered', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_companies_industry_id_industries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_coverage_tier'), 'companies', ['coverage_tier'], unique=False)
    op.create_index(op.f('ix_companies_industry_id'), 'companies', ['industry_id'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('state_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='task_status'), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['research_state.id'], name=op.f('fk_tasks_state_id_research_state'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_state_id'), 'tasks', ['state_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_type'), 'tasks', ['type'], unique=False)
    op.create_table('catalyst_calendar',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('earnings', 'dividend', 'ex_dividend', name='calendar_event_type'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_catalyst_calendar_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalyst_calendar')),
    sa.UniqueConstraint('company_id', 'event_type', 'event_date', name=op.f('uq_catalyst_calendar_company_id'))
    )
    op.create_index(op.f('ix_catalyst_calendar_company_id'), 'catalyst_calendar', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalyst_calendar_event_date'), 'catalyst_calendar', ['event_date'], unique=False)
    op.create_index(op.f('ix_catalyst_calendar_event_type'), 'catalyst_calendar', ['event_type'], unique=False)
    op.create_table('financials',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.Enum('annual', 'quarterly', name='period_type'), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('capex', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_financials_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financials')),
    sa.UniqueConstraint('company_id', 'period_end', 'period_type', name=op.f('uq_financials_company_id'))
    )
    op.create_index(op.f('ix_financials_company_id'), 'financials', ['company_id'], unique=False)
    op.create_index(op.f('ix_financials_period_type'), 'financials', ['period_type'], unique=False)
    op.create_table('fundamental',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('prose', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('rubric_version', sa.String(length=32), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_fundamental_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamental'))
    )
    op.create_index('ix_fundamental_company_generated', 'fundamental', ['company_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_fundamental_company_id'), 'fundamental', ['company_id'], unique=False)
    op.create_index('ix_fundamental_embedding_hnsw', 'fundamental', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('news_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('tickers', postgresql.ARRAY(sa.String(length=20)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('significance', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_news_events_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_events'))
    )
    op.create_index(op.f('ix_news_events_company_id'), 'news_events', ['company_id'], unique=False)
    op.create_index('ix_news_events_embedding_hnsw', 'news_events', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_news_events_published_at'), 'news_events', ['published_at'], unique=False)
    op.create_index('ix_news_events_published_significance', 'news_events', ['published_at', 'significance'], unique=False)
    op.create_index(op.f('ix_news_events_significance'), 'news_events', ['significance'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_prices_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices')),
    sa.UniqueConstraint('company_id', 'date', name=op.f('uq_prices_company_id'))
    )
    op.create_index(op.f('ix_prices_company_id'), 'prices', ['company_id'], unique=False)
    op.create_table('sentimental',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('prose', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('rubric_version', sa.String(length=32), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sentimental_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentimental'))
    )
    op.create_index('ix_sentimental_company_generated', 'sentimental', ['company_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_sentimental_company_id'), 'sentimental', ['company_id'], unique=False)
    op.create_index('ix_sentimental_embedding_hnsw', 'sentimental', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentimental_embedding_hnsw', table_name='sentimental', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_sentimental_company_id'), table_name='sentimental')
    op.drop_index('ix_sentimental_company_generated', table_name='sentimental')
    op.drop_table('sentimental')
    op.drop_index(op.f('ix_prices_company_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_news_events_significance'), table_name='news_events')
    op.drop_index('ix_news_events_published_significance', table_name='news_events')
    op.drop_index(op.f('ix_news_events_published_at'), table_name='news_events')
    op.drop_index('ix_news_events_embedding_hnsw', table_name='news_events', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_news_events_company_id'), table_name='news_events')
    op.drop_table('news_events')
    op.drop_index('ix_fundamental_embedding_hnsw', table_name='fundamental', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_fundamental_company_id'), table_name='fundamental')
    op.drop_index('ix_fundamental_company_generated', table_name='fundamental')
    op.drop_table('fundamental')
    op.drop_index(op.f('ix_financials_period_type'), table_name='financials')
    op.drop_index(op.f('ix_financials_company_id'), table_name='financials')
    op.drop_table('financials')
    op.drop_index(op.f('ix_catalyst_calendar_event_type'), table_name='catalyst_calendar')
    op.drop_index(op.f('ix_catalyst_calendar_event_date'), table_name='catalyst_calendar')
    op.drop_index(op.f('ix_catalyst_calendar_company_id'), table_name='catalyst_calendar')
    op.drop_table('catalyst_calendar')
    op.drop_index(op.f('ix_tasks_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_state_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_coverage_tier'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('user_preferences')
    op.drop_index('ix_research_state_status_active', table_name='research_state')
    op.drop_index(op.f('ix_research_state_status'), table_name='research_state')
    op.drop_index(op.f('ix_research_state_parent_state_id'), table_name='research_state')
    op.drop_index('ix_research_state_embedding_hnsw', table_name='research_state', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('research_state')
    op.drop_index(op.f('ix_notifications_sent_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_industries_key'), table_name='industries')
    op.drop_table('industries')
    op.drop_index(op.f('ix_cache_url'), table_name='cache')
    op.drop_index('ix_cache_fetched_at', table_name='cache')
    op.drop_table('cache')
    op.drop_index('ix_analysis_type_generated', table_name='analysis')
    op.drop_index(op.f('ix_analysis_type'), table_name='analysis')
    op.drop_index('ix_analysis_embedding_hnsw', table_name='analysis', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('analysis')
    # Drop the enum types implicitly created by the tables above.
    for _enum_name in (
        'coverage_tier', 'state_status', 'analysis_type', 'task_status',
        'channel', 'period_type', 'calendar_event_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS {_enum_name}')
    # ### end Alembic commands ###
