"""initial schema

Revision ID: 9ffe6d32b0cd
Revises: 
Create Date: 2026-06-01 06:37:50.685953
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '9ffe6d32b0cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector must exist before any VECTOR column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='job_status'), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('notification_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel', sa.Enum('email', 'imessage', 'whatsapp', 'in_app', name='channel'), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=True),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_history')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notification_history_dedupe_key'))
    )
    op.create_index(op.f('ix_notification_history_channel'), 'notification_history', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_history_sent_at'), 'notification_history', ['sent_at'], unique=False)
    op.create_table('pulse_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slot', sa.Enum('morning', 'midday', 'close', 'on_demand', name='pulse_slot'), nullable=False),
    sa.Column('pulse_snapshot', sa.Text(), nullable=True),
    sa.Column('instruments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    # `channel` type is created by notification_history (above); don't recreate it here.
    sa.Column('channel_sent', postgresql.ENUM('email', 'imessage', 'whatsapp', 'in_app', name='channel', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pulse_runs'))
    )
    op.create_index(op.f('ix_pulse_runs_slot'), 'pulse_runs', ['slot'], unique=False)
    op.create_table('reading_list_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('top_snapshot', sa.Text(), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('source_event_ids', postgresql.ARRAY(sa.BigInteger()), server_default=sa.text("'{}'::bigint[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_list_runs'))
    )
    op.create_table('sectors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sectors'))
    )
    op.create_index(op.f('ix_sectors_key'), 'sectors', ['key'], unique=True)
    op.create_table('user_preferences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('interested_sectors', postgresql.ARRAY(sa.String(length=64)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('pulse_user', postgresql.ARRAY(sa.String(length=32)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('default_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    op.create_table('industries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sector_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_industries_sector_id_sectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industries'))
    )
    op.create_index(op.f('ix_industries_key'), 'industries', ['key'], unique=True)
    op.create_index(op.f('ix_industries_sector_id'), 'industries', ['sector_id'], unique=False)
    op.create_table('sector_aggregate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sector_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('etf_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('breadth', sa.Float(), nullable=True),
    sa.Column('rolled_sentiment', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_sector_aggregate_sector_id_sectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sector_aggregate')),
    sa.UniqueConstraint('sector_id', 'date', name=op.f('uq_sector_aggregate_sector_id'))
    )
    op.create_index(op.f('ix_sector_aggregate_sector_id'), 'sector_aggregate', ['sector_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('sector_id', sa.BigInteger(), nullable=True),
    sa.Column('industry_id', sa.BigInteger(), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('coverage_tier', sa.Enum('watchlist', 'discovered', 'archived', name='coverage_tier'), server_default='discovered', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_companies_industry_id_industries')),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_companies_sector_id_sectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_coverage_tier'), 'companies', ['coverage_tier'], unique=False)
    op.create_index(op.f('ix_companies_industry_id'), 'companies', ['industry_id'], unique=False)
    op.create_index(op.f('ix_companies_sector_id'), 'companies', ['sector_id'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('catalyst_calendar',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('earnings', 'dividend', 'ex_dividend', name='calendar_event_type'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_catalyst_calendar_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalyst_calendar')),
    sa.UniqueConstraint('company_id', 'event_type', 'event_date', name=op.f('uq_catalyst_calendar_company_id'))
    )
    op.create_index(op.f('ix_catalyst_calendar_company_id'), 'catalyst_calendar', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalyst_calendar_event_date'), 'catalyst_calendar', ['event_date'], unique=False)
    op.create_index(op.f('ix_catalyst_calendar_event_type'), 'catalyst_calendar', ['event_type'], unique=False)
    op.create_table('financial_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.Enum('annual', 'quarterly', name='period_type'), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('capex', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_financial_data_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_data')),
    sa.UniqueConstraint('company_id', 'period_end', 'period_type', name=op.f('uq_financial_data_company_id'))
    )
    op.create_index(op.f('ix_financial_data_company_id'), 'financial_data', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_data_period_type'), 'financial_data', ['period_type'], unique=False)
    op.create_table('fundamental_prose',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_fundamental_prose_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamental_prose'))
    )
    op.create_index('ix_fundamental_prose_company_generated', 'fundamental_prose', ['company_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_fundamental_prose_company_id'), 'fundamental_prose', ['company_id'], unique=False)
    op.create_index('ix_fundamental_prose_embedding_hnsw', 'fundamental_prose', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('fundamental_scores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rubric_version', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_fundamental_scores_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamental_scores'))
    )
    op.create_index('ix_fundamental_scores_company_generated', 'fundamental_scores', ['company_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_fundamental_scores_company_id'), 'fundamental_scores', ['company_id'], unique=False)
    op.create_table('news_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('industry_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('tickers', postgresql.ARRAY(sa.String(length=16)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('significance_tier', sa.Enum('routine', 'notable', 'significant', name='significance_tier'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_news_events_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_news_events_industry_id_industries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_events'))
    )
    op.create_index(op.f('ix_news_events_company_id'), 'news_events', ['company_id'], unique=False)
    op.create_index('ix_news_events_embedding_hnsw', 'news_events', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_news_events_industry_id'), 'news_events', ['industry_id'], unique=False)
    op.create_index(op.f('ix_news_events_published_at'), 'news_events', ['published_at'], unique=False)
    op.create_index('ix_news_events_published_significance', 'news_events', ['published_at', 'significance_tier'], unique=False)
    op.create_index(op.f('ix_news_events_significance_tier'), 'news_events', ['significance_tier'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_price_history_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history')),
    sa.UniqueConstraint('company_id', 'date', name=op.f('uq_price_history_company_id'))
    )
    op.create_index(op.f('ix_price_history_company_id'), 'price_history', ['company_id'], unique=False)
    op.create_table('sentimental_prose',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sentimental_prose_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentimental_prose'))
    )
    op.create_index('ix_sentimental_prose_company_generated', 'sentimental_prose', ['company_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_sentimental_prose_company_id'), 'sentimental_prose', ['company_id'], unique=False)
    op.create_index('ix_sentimental_prose_embedding_hnsw', 'sentimental_prose', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('sentimental_scores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rubric_version', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sentimental_scores_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentimental_scores'))
    )
    op.create_index('ix_sentimental_scores_company_generated', 'sentimental_scores', ['company_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_sentimental_scores_company_id'), 'sentimental_scores', ['company_id'], unique=False)
    op.create_table('watchlist_metadata',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('why_added', sa.Text(), nullable=True),
    sa.Column('why_relevant', sa.Text(), nullable=True),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_watchlist_metadata_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_metadata'))
    )
    op.create_index(op.f('ix_watchlist_metadata_company_id'), 'watchlist_metadata', ['company_id'], unique=True)
    op.create_table('citations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('prose_kind', sa.Enum('fundamental', 'sentimental', name='prose_kind'), nullable=False),
    sa.Column('prose_id', sa.BigInteger(), nullable=False),
    sa.Column('news_event_id', sa.BigInteger(), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_event_id'], ['news_events.id'], name=op.f('fk_citations_news_event_id_news_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations'))
    )
    op.create_index(op.f('ix_citations_news_event_id'), 'citations', ['news_event_id'], unique=False)
    op.create_index('ix_citations_prose', 'citations', ['prose_kind', 'prose_id'], unique=False)
    # HNSW indexes (lines above, rendered from the models) use cosine distance — chosen
    # over IVFFlat for better recall at this corpus size with no training step.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_citations_prose', table_name='citations')
    op.drop_index(op.f('ix_citations_news_event_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_watchlist_metadata_company_id'), table_name='watchlist_metadata')
    op.drop_table('watchlist_metadata')
    op.drop_index(op.f('ix_sentimental_scores_company_id'), table_name='sentimental_scores')
    op.drop_index('ix_sentimental_scores_company_generated', table_name='sentimental_scores')
    op.drop_table('sentimental_scores')
    op.drop_index('ix_sentimental_prose_embedding_hnsw', table_name='sentimental_prose', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_sentimental_prose_company_id'), table_name='sentimental_prose')
    op.drop_index('ix_sentimental_prose_company_generated', table_name='sentimental_prose')
    op.drop_table('sentimental_prose')
    op.drop_index(op.f('ix_price_history_company_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_news_events_significance_tier'), table_name='news_events')
    op.drop_index('ix_news_events_published_significance', table_name='news_events')
    op.drop_index(op.f('ix_news_events_published_at'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_industry_id'), table_name='news_events')
    op.drop_index('ix_news_events_embedding_hnsw', table_name='news_events', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_news_events_company_id'), table_name='news_events')
    op.drop_table('news_events')
    op.drop_index(op.f('ix_fundamental_scores_company_id'), table_name='fundamental_scores')
    op.drop_index('ix_fundamental_scores_company_generated', table_name='fundamental_scores')
    op.drop_table('fundamental_scores')
    op.drop_index('ix_fundamental_prose_embedding_hnsw', table_name='fundamental_prose', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_fundamental_prose_company_id'), table_name='fundamental_prose')
    op.drop_index('ix_fundamental_prose_company_generated', table_name='fundamental_prose')
    op.drop_table('fundamental_prose')
    op.drop_index(op.f('ix_financial_data_period_type'), table_name='financial_data')
    op.drop_index(op.f('ix_financial_data_company_id'), table_name='financial_data')
    op.drop_table('financial_data')
    op.drop_index(op.f('ix_catalyst_calendar_event_type'), table_name='catalyst_calendar')
    op.drop_index(op.f('ix_catalyst_calendar_event_date'), table_name='catalyst_calendar')
    op.drop_index(op.f('ix_catalyst_calendar_company_id'), table_name='catalyst_calendar')
    op.drop_table('catalyst_calendar')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_coverage_tier'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_sector_aggregate_sector_id'), table_name='sector_aggregate')
    op.drop_table('sector_aggregate')
    op.drop_index(op.f('ix_industries_sector_id'), table_name='industries')
    op.drop_index(op.f('ix_industries_key'), table_name='industries')
    op.drop_table('industries')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_sectors_key'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_table('reading_list_runs')
    op.drop_index(op.f('ix_pulse_runs_slot'), table_name='pulse_runs')
    op.drop_table('pulse_runs')
    op.drop_index(op.f('ix_notification_history_sent_at'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_channel'), table_name='notification_history')
    op.drop_table('notification_history')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###

    # `channel` (the one enum used by two tables) is dropped with notification_history's
    # inline create_type. The extension is the last thing to go.
    op.execute("DROP EXTENSION IF EXISTS vector")
