"""industry embeddings + news event industry routing

Revision ID: a10d1d3d9b53
Revises: 4ef2478df8d8
Create Date: 2026-06-14 21:03:55.470176
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = 'a10d1d3d9b53'
down_revision: Union[str, None] = '4ef2478df8d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industries', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    op.add_column('industries', sa.Column('embedding_model', sa.String(length=64), nullable=True))
    op.create_index('ix_industries_embedding_hnsw', 'industries', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.add_column('news_events', sa.Column('industry_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_news_events_industry_id'), 'news_events', ['industry_id'], unique=False)
    op.create_foreign_key(op.f('fk_news_events_industry_id_industries'), 'news_events', 'industries', ['industry_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_news_events_industry_id_industries'), 'news_events', type_='foreignkey')
    op.drop_index(op.f('ix_news_events_industry_id'), table_name='news_events')
    op.drop_column('news_events', 'industry_id')
    op.drop_index('ix_industries_embedding_hnsw', table_name='industries', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('industries', 'embedding_model')
    op.drop_column('industries', 'embedding')
    # ### end Alembic commands ###
