"""standardize ticker columns to yfinance symbols

Revision ID: f55510b1e0cd
Revises: 9ffe6d32b0cd
Create Date: 2026-06-01 07:48:52.342362
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f55510b1e0cd'
down_revision: Union[str, None] = '9ffe6d32b0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'ticker',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('news_events', 'tickers',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=16)),
               type_=postgresql.ARRAY(sa.String(length=20)),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('user_preferences', 'pulse_user',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=32)),
               type_=postgresql.ARRAY(sa.String(length=20)),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_preferences', 'pulse_user',
               existing_type=postgresql.ARRAY(sa.String(length=20)),
               type_=postgresql.ARRAY(sa.VARCHAR(length=32)),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('news_events', 'tickers',
               existing_type=postgresql.ARRAY(sa.String(length=20)),
               type_=postgresql.ARRAY(sa.VARCHAR(length=16)),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('companies', 'ticker',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
