"""chat messages and notification content columns

Revision ID: fd3208e91bc6
Revises: aa8f6f8ed894
Create Date: 2026-06-11 13:09:33.723098
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fd3208e91bc6'
down_revision: Union[str, None] = 'aa8f6f8ed894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chat_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['research_state.id'], name=op.f('fk_chat_messages_state_id_research_state'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chat_messages_state_id'), 'chat_messages', ['state_id'], unique=False)
    op.add_column('notifications', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('notifications', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'body')
    op.drop_column('notifications', 'title')
    op.drop_index(op.f('ix_chat_messages_state_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # Drop the enum type implicitly created by chat_messages above.
    op.execute('DROP TYPE IF EXISTS chat_role')
    # ### end Alembic commands ###
