"""tasks token_usage breakdown

Revision ID: 267d55e6ef0c
Revises: 4938c91d8b8f
Create Date: 2026-06-16 19:02:21.713839
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '267d55e6ef0c'
down_revision: Union[str, None] = '4938c91d8b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'token_usage')
    # ### end Alembic commands ###
