"""research session initiated_by

Revision ID: 48255bd474fb
Revises: a10d1d3d9b53
Create Date: 2026-06-15 13:26:33.583309
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48255bd474fb'
down_revision: Union[str, None] = 'a10d1d3d9b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_state', sa.Column('initiated_by', sa.String(length=16), server_default='schedule', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_state', 'initiated_by')
    # ### end Alembic commands ###
