"""research progress heartbeat + task error_kind

Revision ID: 4938c91d8b8f
Revises: 48255bd474fb
Create Date: 2026-06-15 14:40:51.976531
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4938c91d8b8f'
down_revision: Union[str, None] = '48255bd474fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_state', sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('error_kind', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'error_kind')
    op.drop_column('research_state', 'progress')
    # ### end Alembic commands ###
